# -*- coding: utf-8 -*-
"""Gala Groceries_DataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TiuVriQDdyOG7lpClRTmKIrSiGmVqJ1
"""

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

!pip install pandas
!pip install seaborn

import pandas as pd
import seaborn as sns

path = "/content/drive/My Drive/Colab_Notebooks/sample_sales_data.csv"
df = pd.read_csv(path)
#df.drop(columns=["Unnamed: 0"], inplace = True, errors='ignore')
#df.head()
#df.info()

#df.describe()

def plot_continuous_distribution(data: pd.DataFrame = None, column: str = None, height: int = 8):
  _ = sns.displot(data, x=column, kde = True, height=height, aspect=height/5).set(title=f'Distribution of {column}');

def get_unique_values(data, column):
  num_unique_values = len(data[column].unique())
  value_counts = data[column].value_counts()
  print(f"Column: {column} has {num_unique_values} unique values\n")
  print(value_counts)

def plot_categorical_distribution(data: pd.DataFrame = None, column: str = None, height: int = 8, aspect: int = 2):
  _ = sns.catplot(data=data, x=column, kind='count', height=height, aspect=aspect).set(title=f'Distribution of {column}');

#plot_continuous_distribution(df, 'unit_price')
#plot_continuous_distribution(df, 'total')
#plot_categorical_distribution(df, 'category', height=10, aspect=3.5)